//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACOMPAÑANTE
    {
        public ACOMPAÑANTE()
        {
            this.DETALLE_ACOMPAÑANTE = new HashSet<DETALLE_ACOMPAÑANTE>();
        }
    
        public decimal ID_ACOMPAÑANTE { get; set; }
        public string NOMBRE_ACOMPAÑANTE { get; set; }
        public string APELLIDO_ACOMPAÑANTE { get; set; }
        public string RANGO_ETARIO { get; set; }
    
        public virtual ICollection<DETALLE_ACOMPAÑANTE> DETALLE_ACOMPAÑANTE { get; set; }
    }
}
