//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_OUT
    {
        public CHECK_OUT()
        {
            this.DETALLE_CHECKOUT = new HashSet<DETALLE_CHECKOUT>();
        }
    
        public decimal ID_CHECK_OUT { get; set; }
        public string ESTADO_HABITACION { get; set; }
        public Nullable<decimal> MULTA { get; set; }
        public Nullable<decimal> COSTO_REPARACION { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<DETALLE_CHECKOUT> DETALLE_CHECKOUT { get; set; }
    }
}
