//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDUCTOR
    {
        public CONDUCTOR()
        {
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public string RUT_CONDUCTOR { get; set; }
        public string NOMBRE_CONDUCTOR { get; set; }
        public string APELLIDO_CONDUCTOR { get; set; }
        public decimal TRANSPORTE_ID_TRANSPORTE { get; set; }
    
        public virtual TRANSPORTE TRANSPORTE { get; set; }
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
