//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public CONTRATO()
        {
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public decimal ID_CONTRATO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_CONTRATO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO_CONTRATO { get; set; }
        public string PROVEEDOR_ID_PROVEEDOR { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
