//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA_USUARIO
    {
        public CUENTA_USUARIO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public decimal ID_CUENTA_USUARIO { get; set; }
        public string EMAIL_USUARIO { get; set; }
        public string PASSWORD_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public decimal TIPO_USUARIO_ID_TIPO_USUARIO { get; set; }
    
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
