//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_TOUR
    {
        public decimal ID_DETALLE_TOUR { get; set; }
        public decimal RESERVA_ID_RESERVA { get; set; }
        public decimal TOUR_ID_TOUR { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
