//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ACOMPAÑANTE
    {
        public decimal ID_DETALLE_ACOMPAÑANTE { get; set; }
        public decimal ACOMPAÑANTE_ID_ACOMPAÑANTE { get; set; }
        public string USUARIO_RUT_USUARIO { get; set; }
    
        public virtual ACOMPAÑANTE ACOMPAÑANTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
