//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SERVICIO_EXTRA
    {
        public decimal ID_DETALLE_SERVICIO_EXTRA { get; set; }
        public decimal SERVICIO_ID_SERVICIO { get; set; }
        public decimal SERVICIO_CONTRATO_ID_CONTRATO { get; set; }
        public string SERVICIO_CONTRATO_PROVEEDOR_ID_PROVEEDOR { get; set; }
        public decimal RESERVA_ID_RESERVA { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
