//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_PAGO
    {
        public ESTADO_PAGO()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public decimal ID_ESTADO_PAGO { get; set; }
        public string ESTADO_PAGO1 { get; set; }
    
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
