//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPUESTO
    {
        public IMPUESTO()
        {
            this.DETALLE_IMPUESTO = new HashSet<DETALLE_IMPUESTO>();
        }
    
        public decimal ID_IMPUESTO { get; set; }
        public Nullable<decimal> MONTO_CONTRIBUCION { get; set; }
        public Nullable<decimal> MONTO_DIVIDENDO { get; set; }
    
        public virtual ICollection<DETALLE_IMPUESTO> DETALLE_IMPUESTO { get; set; }
    }
}
