//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENCION
    {
        public MANTENCION()
        {
            this.DETALLE_MANTENCION = new HashSet<DETALLE_MANTENCION>();
        }
    
        public decimal ID_MANTENCION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_MANTENCION { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO_MANTENCION { get; set; }
        public Nullable<decimal> COSTO_MANTENCION { get; set; }
    
        public virtual ICollection<DETALLE_MANTENCION> DETALLE_MANTENCION { get; set; }
    }
}
