//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public decimal ID_PAGO { get; set; }
        public string FORMA_PAGO { get; set; }
        public Nullable<decimal> MONTO_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public decimal ESTADO_PAGO_ID_ESTADO_PAGO { get; set; }
        public decimal RESERVA_ID_RESERVA { get; set; }
    
        public virtual ESTADO_PAGO ESTADO_PAGO { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
