//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public string ID_PROVEEDOR { get; set; }
        public string NOMBRE_PROVEEDOR { get; set; }
    
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
    }
}
