//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public TRANSPORTE()
        {
            this.CONDUCTOR = new HashSet<CONDUCTOR>();
        }
    
        public decimal ID_TRANSPORTE { get; set; }
        public string LUGAR_RECOGIDA { get; set; }
        public Nullable<System.DateTime> FECHA_RECOGIDA { get; set; }
        public decimal RESERVA_ID_RESERVA { get; set; }
    
        public virtual ICollection<CONDUCTOR> CONDUCTOR { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
