//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TurismoRealWebEntities : DbContext
    {
        public TurismoRealWebEntities()
            : base("name=TurismoRealWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACOMPAÑANTE> ACOMPAÑANTE { get; set; }
        public DbSet<CHECK_OUT> CHECK_OUT { get; set; }
        public DbSet<CHECKLIST_ESTADO_INVENTARIO> CHECKLIST_ESTADO_INVENTARIO { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<CONDUCTOR> CONDUCTOR { get; set; }
        public DbSet<CONTRATO> CONTRATO { get; set; }
        public DbSet<CUENTA_USUARIO> CUENTA_USUARIO { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<DETALLE_ACOMPAÑANTE> DETALLE_ACOMPAÑANTE { get; set; }
        public DbSet<DETALLE_CHECKOUT> DETALLE_CHECKOUT { get; set; }
        public DbSet<DETALLE_IMPUESTO> DETALLE_IMPUESTO { get; set; }
        public DbSet<DETALLE_INVENTARIO> DETALLE_INVENTARIO { get; set; }
        public DbSet<DETALLE_MANTENCION> DETALLE_MANTENCION { get; set; }
        public DbSet<DETALLE_RESERVA> DETALLE_RESERVA { get; set; }
        public DbSet<DETALLE_SERVICIO_EXTRA> DETALLE_SERVICIO_EXTRA { get; set; }
        public DbSet<DETALLE_TOUR> DETALLE_TOUR { get; set; }
        public DbSet<ESTADO_PAGO> ESTADO_PAGO { get; set; }
        public DbSet<IMPUESTO> IMPUESTO { get; set; }
        public DbSet<MANTENCION> MANTENCION { get; set; }
        public DbSet<OBJETO_HABITACION> OBJETO_HABITACION { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<PROVINCIA> PROVINCIA { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public DbSet<TOUR> TOUR { get; set; }
        public DbSet<TRANSPORTE> TRANSPORTE { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VEHICULO> VEHICULO { get; set; }
    
        public virtual int SP_CREATE_RESERVA(Nullable<System.DateTime> r_FECHA_ENTRADA, Nullable<System.DateTime> r_FECHA_SALIDA, string r_FIRMA_CONFORMIDAD_CLIENTE, string r_ID_USUARIO)
        {
            var r_FECHA_ENTRADAParameter = r_FECHA_ENTRADA.HasValue ?
                new ObjectParameter("R_FECHA_ENTRADA", r_FECHA_ENTRADA) :
                new ObjectParameter("R_FECHA_ENTRADA", typeof(System.DateTime));
    
            var r_FECHA_SALIDAParameter = r_FECHA_SALIDA.HasValue ?
                new ObjectParameter("R_FECHA_SALIDA", r_FECHA_SALIDA) :
                new ObjectParameter("R_FECHA_SALIDA", typeof(System.DateTime));
    
            var r_FIRMA_CONFORMIDAD_CLIENTEParameter = r_FIRMA_CONFORMIDAD_CLIENTE != null ?
                new ObjectParameter("R_FIRMA_CONFORMIDAD_CLIENTE", r_FIRMA_CONFORMIDAD_CLIENTE) :
                new ObjectParameter("R_FIRMA_CONFORMIDAD_CLIENTE", typeof(string));
    
            var r_ID_USUARIOParameter = r_ID_USUARIO != null ?
                new ObjectParameter("R_ID_USUARIO", r_ID_USUARIO) :
                new ObjectParameter("R_ID_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_RESERVA", r_FECHA_ENTRADAParameter, r_FECHA_SALIDAParameter, r_FIRMA_CONFORMIDAD_CLIENTEParameter, r_ID_USUARIOParameter);
        }
    
        public virtual int SP_CREATE_USUARIO(string v_RUT_USUARIO, string v_NOMBRE, string v_APELLIDO, string v_EMAIL, string v_DIRECCION, string v_TELEFONO, Nullable<decimal> v_ID_CUENTA_USUARIO)
        {
            var v_RUT_USUARIOParameter = v_RUT_USUARIO != null ?
                new ObjectParameter("V_RUT_USUARIO", v_RUT_USUARIO) :
                new ObjectParameter("V_RUT_USUARIO", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_APELLIDOParameter = v_APELLIDO != null ?
                new ObjectParameter("V_APELLIDO", v_APELLIDO) :
                new ObjectParameter("V_APELLIDO", typeof(string));
    
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_TELEFONOParameter = v_TELEFONO != null ?
                new ObjectParameter("V_TELEFONO", v_TELEFONO) :
                new ObjectParameter("V_TELEFONO", typeof(string));
    
            var v_ID_CUENTA_USUARIOParameter = v_ID_CUENTA_USUARIO.HasValue ?
                new ObjectParameter("V_ID_CUENTA_USUARIO", v_ID_CUENTA_USUARIO) :
                new ObjectParameter("V_ID_CUENTA_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_USUARIO", v_RUT_USUARIOParameter, v_NOMBREParameter, v_APELLIDOParameter, v_EMAILParameter, v_DIRECCIONParameter, v_TELEFONOParameter, v_ID_CUENTA_USUARIOParameter);
        }
    
        public virtual int SP_DELETE_RESERVA(Nullable<decimal> v_ID_RESERVA)
        {
            var v_ID_RESERVAParameter = v_ID_RESERVA.HasValue ?
                new ObjectParameter("V_ID_RESERVA", v_ID_RESERVA) :
                new ObjectParameter("V_ID_RESERVA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_RESERVA", v_ID_RESERVAParameter);
        }
    
        public virtual int SP_UPDATE_RESERVA(Nullable<decimal> v_ID_RESERVA, Nullable<System.DateTime> v_FECHA_ENTRADA, Nullable<System.DateTime> v_FECHA_SALIDA, string v_FIRMA_CONFORMIDAD_CLIENTE, Nullable<decimal> v_ID_USUARIO)
        {
            var v_ID_RESERVAParameter = v_ID_RESERVA.HasValue ?
                new ObjectParameter("V_ID_RESERVA", v_ID_RESERVA) :
                new ObjectParameter("V_ID_RESERVA", typeof(decimal));
    
            var v_FECHA_ENTRADAParameter = v_FECHA_ENTRADA.HasValue ?
                new ObjectParameter("V_FECHA_ENTRADA", v_FECHA_ENTRADA) :
                new ObjectParameter("V_FECHA_ENTRADA", typeof(System.DateTime));
    
            var v_FECHA_SALIDAParameter = v_FECHA_SALIDA.HasValue ?
                new ObjectParameter("V_FECHA_SALIDA", v_FECHA_SALIDA) :
                new ObjectParameter("V_FECHA_SALIDA", typeof(System.DateTime));
    
            var v_FIRMA_CONFORMIDAD_CLIENTEParameter = v_FIRMA_CONFORMIDAD_CLIENTE != null ?
                new ObjectParameter("V_FIRMA_CONFORMIDAD_CLIENTE", v_FIRMA_CONFORMIDAD_CLIENTE) :
                new ObjectParameter("V_FIRMA_CONFORMIDAD_CLIENTE", typeof(string));
    
            var v_ID_USUARIOParameter = v_ID_USUARIO.HasValue ?
                new ObjectParameter("V_ID_USUARIO", v_ID_USUARIO) :
                new ObjectParameter("V_ID_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_RESERVA", v_ID_RESERVAParameter, v_FECHA_ENTRADAParameter, v_FECHA_SALIDAParameter, v_FIRMA_CONFORMIDAD_CLIENTEParameter, v_ID_USUARIOParameter);
        }
    
        public virtual int SP_UPDATE_USUARIO(string v_RUT_USUARIO, string v_NOMBRE, string v_APELLIDO, string v_EMAIL, string v_DIRECCION, string v_TELEFONO, Nullable<decimal> v_ID_CUENTA_USUARIO)
        {
            var v_RUT_USUARIOParameter = v_RUT_USUARIO != null ?
                new ObjectParameter("V_RUT_USUARIO", v_RUT_USUARIO) :
                new ObjectParameter("V_RUT_USUARIO", typeof(string));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_APELLIDOParameter = v_APELLIDO != null ?
                new ObjectParameter("V_APELLIDO", v_APELLIDO) :
                new ObjectParameter("V_APELLIDO", typeof(string));
    
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_TELEFONOParameter = v_TELEFONO != null ?
                new ObjectParameter("V_TELEFONO", v_TELEFONO) :
                new ObjectParameter("V_TELEFONO", typeof(string));
    
            var v_ID_CUENTA_USUARIOParameter = v_ID_CUENTA_USUARIO.HasValue ?
                new ObjectParameter("V_ID_CUENTA_USUARIO", v_ID_CUENTA_USUARIO) :
                new ObjectParameter("V_ID_CUENTA_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_USUARIO", v_RUT_USUARIOParameter, v_NOMBREParameter, v_APELLIDOParameter, v_EMAILParameter, v_DIRECCIONParameter, v_TELEFONOParameter, v_ID_CUENTA_USUARIOParameter);
        }
    }
}
