//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACOMPAÑANTE
    {
        public ACOMPAÑANTE()
        {
            this.DETALLE_ACOMPAÑANTE = new HashSet<DETALLE_ACOMPAÑANTE>();
        }
    
        public decimal ID_ACOMPAÑANTE { get; set; }
        public string NOMBRE_ACOMPAÑANTE { get; set; }
        public string APELLIDO_ACOMPAÑANTE { get; set; }
        public string RANGO_ETARIO { get; set; }
    
        public virtual ICollection<DETALLE_ACOMPAÑANTE> DETALLE_ACOMPAÑANTE { get; set; }
    }
}
