//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKLIST_ESTADO_INVENTARIO
    {
        public decimal ID_CHECK_LIST { get; set; }
        public string ESTADO_CHECK_LIST { get; set; }
        public decimal OBJETO_HABITACION_ID_OBJETO_HABITACION { get; set; }
    
        public virtual OBJETO_HABITACION OBJETO_HABITACION { get; set; }
    }
}
