//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_OUT
    {
        public CHECK_OUT()
        {
            this.DETALLE_CHECKOUT = new HashSet<DETALLE_CHECKOUT>();
        }
    
        public decimal ID_CHECK_OUT { get; set; }
        public string ESTADO_HABITACION { get; set; }
        public Nullable<decimal> MULTA { get; set; }
        public Nullable<decimal> COSTO_REPARACION { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<DETALLE_CHECKOUT> DETALLE_CHECKOUT { get; set; }
    }
}
