//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public CONTRATO()
        {
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public decimal ID_CONTRATO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_CONTRATO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO_CONTRATO { get; set; }
        public string PROVEEDOR_ID_PROVEEDOR { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
