//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA_USUARIO
    {
        public CUENTA_USUARIO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public decimal ID_CUENTA_USUARIO { get; set; }
        public string EMAIL_USUARIO { get; set; }
        public string PASSWORD_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public decimal TIPO_USUARIO_ID_TIPO_USUARIO { get; set; }
    
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
