//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ACOMPAÑANTE
    {
        public decimal ID_DETALLE_ACOMPAÑANTE { get; set; }
        public decimal ACOMPAÑANTE_ID_ACOMPAÑANTE { get; set; }
        public string USUARIO_RUT_USUARIO { get; set; }
    
        public virtual ACOMPAÑANTE ACOMPAÑANTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
