//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CHECKOUT
    {
        public decimal ID_DETALLE_CHECKOUT { get; set; }
        public Nullable<decimal> RESERVA_ID_RESERVA { get; set; }
        public Nullable<decimal> CHECK_OUT_ID_CHECK_OUT { get; set; }
    
        public virtual CHECK_OUT CHECK_OUT { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
