//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_PAGO
    {
        public ESTADO_PAGO()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public decimal ID_ESTADO_PAGO { get; set; }
        public string ESTADO_PAGO1 { get; set; }
    
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
