//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENCION
    {
        public MANTENCION()
        {
            this.DETALLE_MANTENCION = new HashSet<DETALLE_MANTENCION>();
        }
    
        public decimal ID_MANTENCION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO_MANTENCION { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO_MANTENCION { get; set; }
        public Nullable<decimal> COSTO_MANTENCION { get; set; }
    
        public virtual ICollection<DETALLE_MANTENCION> DETALLE_MANTENCION { get; set; }
    }
}
