//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.PROVINCIA = new HashSet<PROVINCIA>();
        }
    
        public decimal ID_REGION { get; set; }
        public string NOMBRE_REGION { get; set; }
    
        public virtual ICollection<PROVINCIA> PROVINCIA { get; set; }
    }
}
