//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.DETALLE_CHECKOUT = new HashSet<DETALLE_CHECKOUT>();
            this.DETALLE_RESERVA = new HashSet<DETALLE_RESERVA>();
            this.DETALLE_SERVICIO_EXTRA = new HashSet<DETALLE_SERVICIO_EXTRA>();
            this.DETALLE_TOUR = new HashSet<DETALLE_TOUR>();
            this.PAGO = new HashSet<PAGO>();
            this.TRANSPORTE = new HashSet<TRANSPORTE>();
        }
    
        public decimal ID_RESERVA { get; set; }
        public Nullable<System.DateTime> FECHA_ENTRADA { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public string FIRMA_CONFORMIDAD_CLIENTE { get; set; }
        public string USUARIO_ID_USUARIO { get; set; }
    
        public virtual ICollection<DETALLE_CHECKOUT> DETALLE_CHECKOUT { get; set; }
        public virtual ICollection<DETALLE_RESERVA> DETALLE_RESERVA { get; set; }
        public virtual ICollection<DETALLE_SERVICIO_EXTRA> DETALLE_SERVICIO_EXTRA { get; set; }
        public virtual ICollection<DETALLE_TOUR> DETALLE_TOUR { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<TRANSPORTE> TRANSPORTE { get; set; }
    }
}
