//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_USUARIO
    {
        public TIPO_USUARIO()
        {
            this.CUENTA_USUARIO = new HashSet<CUENTA_USUARIO>();
        }
    
        public decimal ID_TIPO_USUARIO { get; set; }
        public string NOMBRE_TIPO_USUARIO { get; set; }
        public string TIPO_PERFIL { get; set; }
    
        public virtual ICollection<CUENTA_USUARIO> CUENTA_USUARIO { get; set; }
    }
}
