//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        public TOUR()
        {
            this.DETALLE_TOUR = new HashSet<DETALLE_TOUR>();
        }
    
        public decimal ID_TOUR { get; set; }
        public string NOMBRE_TOUR { get; set; }
        public Nullable<System.DateTime> FECHA_TOUR { get; set; }
        public Nullable<decimal> COSTO_TOUR { get; set; }
        public string DESCRIPCION_TOUR { get; set; }
    
        public virtual ICollection<DETALLE_TOUR> DETALLE_TOUR { get; set; }
    }
}
