//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public TRANSPORTE()
        {
            this.CONDUCTOR = new HashSet<CONDUCTOR>();
        }
    
        public decimal ID_TRANSPORTE { get; set; }
        public string LUGAR_RECOGIDA { get; set; }
        public Nullable<System.DateTime> FECHA_RECOGIDA { get; set; }
        public decimal RESERVA_ID_RESERVA { get; set; }
    
        public virtual ICollection<CONDUCTOR> CONDUCTOR { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
