//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoRealWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public string PATENTE { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string CONDUCTOR_RUT_CONDUCTOR { get; set; }
    
        public virtual CONDUCTOR CONDUCTOR { get; set; }
    }
}
